### ISSUE TITLE
Add test for CPU decoding with WNMT models

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-regression-tests#10]
Add test for CPU decoding with WNMT models, especially for AAN layers.

**Comment by snukky** [comment]
I was thinking about making regression tests from the benchmarks we created for WNMT. 

I'm not sure we may assume that, for instance, the regression test will fail if the decoding time is 1.5x/2x slower than expected on a specific GPU. Instead we can generate logs and compare the performance with historic decoding times.

Of course, measuring the decoding speed would be in addition to checking translation outputs.

**Comment by emjotde** [comment]
I wouldn't bother too much with speed measurements. I'm aiming more for correct outputs.

**Comment by snukky** [comment]
I added three tests: a small student model w/ and w/o AAN + a small student model with AAN and `--optimize`.
