### ISSUE TITLE
Tests are failing on Titan Xp but pass on Titan X

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian-regression-tests#12]
```
  - tests/decoder/align/test_align_nbest.sh
  - tests/training/restarting/test_sgd_for_two_epochs.sh
  - tests/training/exp-smoothing/test_expsmooth.sh
  - tests/training/exp-smoothing/test_expsmooth_sync.sh
  - tests/training/restoring/validation/test_adding_validator_after_restart.sh
  - tests/training/restoring/validation/test_restoring_validation_lower_is_better.sh
  - tests/training/restoring/optimizer/test_adagrad_params.sh
  - tests/training/restoring/optimizer/test_adam_params.sh
  - tests/training/restoring/optimizer/test_adam_params_async.sh
  - tests/training/restoring/optimizer/test_adam_params_sync.sh
  - tests/training/multi-gpu/test_sync_sgd.sh
  - tests/training/basics/test_valid_script.sh
```

These are mostly new tests, right?

**Comment by emjotde** [comment]
Actually, these fail on Titan X too:
```
  - tests/training/cost-functions/test_perplexity.sh
  - tests/training/restoring/validation/test_adding_validator_after_restart.sh
  - tests/decoder/align/test_align_nbest.sh
  - tests/decoder/align-ensemble/test_align_ensemble.sh
  - tests/decoder/align-ensemble/test_align_ensemble_beam_1.sh
```
This is all for current master.

**Comment by emjotde** [comment]
Seems we have some strong instability issues?

**Comment by snukky** [comment]
Only `training/exp-smoothing` and `decoder/align` are relatively new. I forgot to use float comparison in the alignment tests (fixed now), but all other tests pass for me on Titan X on marian-nmt/marian-dev@8b0e2f9. I'll check again with the most recent version of master.

And yes, that's my observation too, so tests for training are adjusted to graphic card types I have access to. I don't think I have access to Titan Xp. The instability even increases for (a)synchronous and is pretty high for Adam comparing to SGD. 
Nevertheless, decoder tests should be stable and pass on any GPU.

**Comment by snukky** [comment]
Do you have Titan X and Titan Xp on the same machine? If not, are the numpy versions the same on both? Some tests failed because of differences how numpy prints matrices on stdout. Should be solved now. I also increased the precision in two tests, and now all tests pass for me on Titan Black, 1080 Ti, and Titan X with the current master.
Please check if tests still fail on your Titan Xp.

**Comment by emjotde** [comment]
This was a problem with left-over files.
