### ISSUE TITLE
~/tools/marian-dev/build/marian-scorer -m model.npz -t train.BPE -v vocab.yml > train.lm.score --devices 3

### ISSUE THREAD

**Issue by prigioni** [marian-nmt/marian-regression-tests#22]
Error: Number of examples and labels does not match: -32567 != 47744
Error: Aborted from marian::CrossEntropyNodeOp::CrossEntropyNodeOp(marian::Expr, marian::Expr)

**Comment by snukky** [comment]
Is this an error you are getting from some of our regression tests or from a model you have trained yourself?

**Comment by prigioni** [comment]
> Is this an error you are getting from some of our regression tests or from a model you have trained yourself?

I trained model by myself and I have soved the problem by reducing the sentence length.
