### ISSUE TITLE
Missing corpus for tests/sentencepiece/setup.sh

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-regression-tests#27]
`tests/sentencepiece/setup.sh` fails these tests
```
test -f $MRT_DATA/europarl.de-en/corpus.small.en.gz || exit 1
test -f $MRT_DATA/europarl.de-en/corpus.small.de.gz || exit 1
```

Running the command 
```
make install
```
does not provision them. This issue filing pertains to commit db743d7, which appears to be the current version in the master branch of marian (commit d72cae5ebe27d512eeb35dc45c03dddef40e7989)

**Comment by snukky** [comment]
This has been fixed in the master branch, I just updated the submodule in the marian-dev repo. Thanks!
