### ISSUE TITLE
Add test for compiling with -DBUILD_ARCH=x86-64

### ISSUE THREAD

**Issue by ugermann** [marian-nmt/marian-regression-tests#35]

**Comment by ugermann** [comment]
Related to https://github.com/marian-nmt/marian-dev/issues/559.
Testing that Marian compiles on old CPU architectures would be helpful to ensure that dockerized versions of Marian will run everywhere. Ideally -DBUILD_ARCH=x86-64, or whatever the minimal required hardware is (which should be documented).

**Comment by snukky** [comment]
Closing as it's 3+ year old now and unlikely still needed. We haven't added compilation tests to this repo, this is available in our GitHub Actions pipelines, but it supports relatively new machines only.
