### ISSUE TITLE
test_char_s2s.sh fails if no GPU is present

### ISSUE THREAD

**Issue by kdavis-mozilla** [marian-nmt/marian-regression-tests#48]
As the tests should be viable with or without GPU's being present, having `test_char_s2s.sh` fail if `MRT_MARIAN_USE_CUDNN` is not sets doesn't seem like proper behavior.

**Comment by snukky** [comment]
This test should be permanently turned off. How do you call the `./run_mrt.sh`? 

I guess that might be a bug because all files and directories with names starting with an underscore should not be run.

Do you run `marian-dev/regression-tests` or the master of marian-regression-tests?

**Comment by kdavis-mozilla** [comment]
I run each test tests as follows:

> `./run_mrt.sh tests/training/basics/test_valid_script.sh`

for every script prefixed with `test_` in the `tests` directory. I have to run test separately to integrate into our CI.

But if tests in files and directories starting with an underscore should not be run. I can remove these tests.

**Comment by snukky** [comment]
For me, the command

    ./run_mrt.sh  tests/models/_char-s2s/test_char_s2s.sh

does not run any test. And this is correct.
